// error handling in js
function foo(){
    try{

    }
    catch(e){

    }
}
//executes when a JS promise that has no rejection handler is rejected

window.addEventListener('unhandledrejection', function () { });